### ISSUE TITLE
Why links don't work correct

### ISSUE THREAD

**Issue by dev-msln** [py-pa/django-minio-storage#107]
I set the settings and uploaded some files with django FileFields.
Now when I click on the file url, it will not be downloaded, it redirects me to minio browser to download file.

In the production it's not a best practice to redirect user to minio browser.
Is there any way to solve this problem?
Thanks

**Comment by Cheng-2v** [comment]
you should execute `mc policy set none bucketname` to unset policy of the specific bucket

**Comment by dev-msln** [comment]
> you should execute `mc policy set none bucketname` to unset policy of the specific bucket

Sorry man, I forgot to set `MINIO_STORAGE_MEDIA_USE_PRESIGNED` to True. I set it to True and problem solved.
