### ISSUE TITLE
Version 0.3.9 update not found only 0.3.9.linux-x86_64

### ISSUE THREAD

**Issue by dominik-bln** [py-pa/django-minio-storage#108]
We are using Poetry to install our dependencies and are getting a strange message when trying to apply the update to `0.3.9`:

<img width="1113" alt="Screenshot 2020-09-02 at 10 27 04" src="https://user-images.githubusercontent.com/855119/91957930-fab56500-ed06-11ea-87bd-6cabe0abc98c.png">

**Comment by dominik-bln** [comment]
Now that I look again, I also don't see `0.3.9` in the release list here, but there is something on PyPI and our renovate bot thought it should update..

**Comment by thomasf** [comment]
I just had not pushed the tag

**Comment by jayvdb** [comment]
@thomasf 
I still get that error in `poetry update`.

https://pypi.org/project/django-minio-storage/#files only contains
`django-minio-storage-0.3.9.linux-x86_64.tar.gz                                           (22.5 kB) | Source | None | Aug 28, 2020`


```
  - Updating django-minio-storage (0.3.7 -> 0.3.9)

  EnvCommandError

  Command ['/home/jayvdb/.cache/pypoetry/virtualenvs/django-backend-tUiU8616-py3.8/bin/pip', 'install', '--no-deps', '-U', 'django-minio-storage==0.3.9'] errored with the following return code 1, and output: 
  Collecting django-minio-storage==0.3.9
    ERROR: Could not find a version that satisfies the requirement django-minio-storage==0.3.9 (from versions: 0.3.9.linux-x86_64, 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8)
  ERROR: No matching distribution found for django-minio-storage==0.3.9
```

**Comment by jayvdb** [comment]
`poetry add 'django-minio-storage!=0.3.9'` fixes it for me.

**Comment by thomasf** [comment]
Yeah, something is maybe weird with that release.. will look at it later this week.

**Comment by thomasf** [comment]
the source archive is missing on pypi, that probably the reason. Or there is a sdist but it's platform specific which I don't understand.. Might need a 0.3.10 release to fix this, I have probably uploaded the files wrongly.

**Comment by thomasf** [comment]
I have deleted the broken 0.3.9 release from pypi now.. Since I somehow uploaded an architecture and platform specific sdist archive pypi says I can't replace it so I'll have to release 0.3.10 later this week after figuring out why the this happened.
