### ISSUE TITLE
minio 7 support

### ISSUE THREAD

**Issue by jayvdb** [py-pa/django-minio-storage#111]
minio v7 API breaks django-minio-storage during import.

https://github.com/py-pa/django-minio-storage/pull/110 is a temporary fix.

**Comment by bhuiyanmobasshir94** [comment]
Specifically, on 7.0.1 I really found a huge change in file names, like `SessConfig`, `Rule` classes have been defined separately in a particular module. It is really needed as we are working on a production-level project with this module.

**Comment by thomasf** [comment]
released in v0.5.0
