### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by riccardogl** [py-pa/django-minio-storage#113]
Hi, I encountered an error `(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1125)'))) `  when I run my django app and minio with self signed certificate. There is no problem if I run minio without the ssl.

here is my settings:

STATIC_URL` = '/static/'
STATIC_ROOT = './static_files/'

DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = '127.0.0.1:443'
MINIO_STORAGE_ACCESS_KEY = 'test'
MINIO_STORAGE_SECRET_KEY = 'test'
MINIO_STORAGE_USE_HTTPS = True
MINIO_STORAGE_MEDIA_BUCKET_NAME = 'media'
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = 'static'
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True

 Anyone encountered such issue?

**Comment by thomasf** [comment]
If you use a self signed certificate you need to set up your http client and minio client to use that certificate. You probably need to create your own subclass of minio storage to do it.
