### ISSUE TITLE
Cannot save files larger than 48.8 GiB

### ISSUE THREAD

**Issue by brianhelba** [py-pa/django-minio-storage#114]
Currently, saving an object calls [`Minio.put_object`](https://github.com/minio/minio-py/blob/307fffe5db5775ed2e1fb0981a778a6b63bb6371/minio/api.py#L987-L990) without an explicit `part_size` argument. Accordingly, `part_size` defaults to 5 MiB. Since the maximum number of parts is 10,000, the maximum savable file size is 50,000 MiB ~= 48 GiB.

It looks like in `minio-py` v7, [the part size is computed dynamically](https://github.com/minio/minio-py/blob/fe78f929454f536942dc13169b20c3c30b8e65ed/minio/api.py#L1711), so this problem would not occur with that API.

An alternative to upgrading to `minio-py` would be to compute an optimal (or at least valid) part size within this library, then passing it explicitly `Minio.put_object`.

**Comment by thomasf** [comment]
minio-py is upgraded to v7, closing this issue for now.
