### ISSUE TITLE
Supported docker image

### ISSUE THREAD

**Issue by facorazza** [py-pa/django-minio-storage#115]
What's the latest minio [release](https://hub.docker.com/r/minio/minio/tags) that works with this module?

**Comment by thomasf** [comment]
For the basic file get/put/list object operations any version should work.  It's the same aws s3 protocol as it always has been.

**Comment by facorazza** [comment]
Ok thanks. So what's the API v7 all about? Is it unrelated to the s3 protocol?

**Comment by thomasf** [comment]
That is the python minio sdk version, not minio itself.

There are probably minio specific extensions and new features that are supported to the V7 client but basic object operations will work with more or less any S3 compatible client library.

**Comment by facorazza** [comment]
I see thanks
