### ISSUE TITLE
Unnecessary HTTP Request for Region Check when Generating Presigned URLs

### ISSUE THREAD

**Issue by krystofbe** [py-pa/django-minio-storage#129]
**Bug Description:**

I have noticed that whenever I attempt to generate a presigned URL using the django-minio-storage library, there is an additional HTTP request made to Minio to check for the region. This process seems unnecessary and adds approximately 200ms of delay to each request on my server. I believe there should be an option to provide the region directly to the Minio Client somewhere here

`https://github.com/py-pa/django-minio-storage/blob/176c9cbbeb47ac1eade346a51197304bbca11677/minio_storage/storage.py#L366`

**Expected Behavior:**
I suggest adding an option to the Minio Client configuration to allow users to supply the region for each bucket individually. This change would eliminate the need for an extra HTTP request to check the region, reducing the delay introduced during the generation of presigned URLs.

**Steps to Reproduce:**

1.  Use the django-minio-storage library to generate a presigned URL.
2.  Observe the network traffic and notice the additional HTTP request made to check for the region.

**Impact:**

The current implementation causes a noticeable delay of approximately 200ms per request on the server when generating presigned URLs. By providing an option to supply the region for each bucket directly to the Minio Client, this unnecessary HTTP request can be eliminated, resulting in improved performance and reduced latency for applications utilizing django-minio-storage.

Please let me know if you require any additional information or clarification regarding this issue.

**Comment by thomasf** [comment]
This was not the behavior before. Something probably happened to the logic for avoiding that after the upgrade to minio-py 7.x

**Comment by thomasf** [comment]
This is probably wrong https://github.com/py-pa/django-minio-storage/blame/master/minio_storage/storage.py#L116

But yes, I agree. It should be possible to specify the region in the settings as well.

**Comment by krystofbe** [comment]
> This is probably wrong https://github.com/py-pa/django-minio-storage/blame/master/minio_storage/storage.py#L116

Yes, this is the place.

> But yes, I agree. It should be possible to specify the region in the settings as well.

Would you like me to create a pull request with the change?

**Comment by thomasf** [comment]
That would be great! 

I am thinking about maybe it's worth ditching all of the base_url_client stuff and just mentioning in the settings docs that region should be set for presigned URL latency.

**Comment by thomasf** [comment]
base_url_client seems to do some other things related to the base url because tests fails when it's removed so just add the region setting for now.

```
FAILED tests/test_app/tests/retrieve_tests.py::URLTests::test_presigned_base_url - AssertionError: Regex didn't match: '^http://example11.com/foo/1\\?' not found in 'http://localhost:9153/foo/1?X-Amz-Algorithm=AWS4-H...
FAILED tests/test_app/tests/retrieve_tests.py::URLTests::test_presigned_base_url_subpath - AssertionError: Regex didn't match: '^http://example11.com/foo/1/555/666/777\\?' not found in 'http://localhost:9153/foo/1/555/666/77...
FAILED tests/test_app/tests/retrieve_tests.py::URLTests::test_quote_base_url_presigned - AssertionError: False is not true
```

**Comment by krystofbe** [comment]
fixed with: https://github.com/py-pa/django-minio-storage/commit/7782818112eba8ae60a6603fb3baa9b1e6c63643
