### ISSUE TITLE
Minio 7.1.16 removed the second parameter of  minio.api.Minio._get_region

### ISSUE THREAD

**Issue by ettoreleandrotognoli** [py-pa/django-minio-storage#135]
I got this error
```
Minio._get_region() takes 2 positional arguments but 3 were given
````
from this line
https://github.com/py-pa/django-minio-storage/blob/c01f000c1d68e4024a5bafbee8eb040c546ecd8b/minio_storage/storage.py#L116

Looks that minio 7.1.16 removed the second parameter on this commit:

https://github.com/minio/minio-py/commit/402f25e56ade2c85d25057217348e3e5d50eae65

**Comment by ettoreleandrotognoli** [comment]
I just rollback my application to minio==7.1.15, and  it is working again

**Comment by thomasf** [comment]
We probably should require the AWS region to be configured in settings instead of doing all this reaching into minio-py internals but let's get this fix released asap.

**Comment by harshavardhana** [comment]
Unexported functions i.e not with `_` - must not be used or relied upon generally speaking.
