### ISSUE TITLE
...PARTIAL_URL_BASE setting still required when ...PARTIAL_URL=False

### ISSUE THREAD

**Issue by thomasf** [py-pa/django-minio-storage#18]
An exception is raised...

I haven't looked into the details of how features but it seems to be that the  `MINIO_PARTIAL_URL` setting  can be made implicit if `MINIO_PARTIAL_URL_BASE` is set?

If the need for two settings goes away `MINIO_PARTIAL_URL`  can become the base url setting itself. 
It can default to `None` or which disables the feature.

 @fazpu ?

**Comment by fazpu** [comment]
Hi, sounds good. Yes, the MINIO_PARTIAL_URL can be removed.
I'll do a PR early next week.

**Comment by thomasf** [comment]
...BASE_URL is maybe a better name than ...PARTIAL_URL

**Comment by thomasf** [comment]
its called `base_url` in djangos own filesystem storage so I think we should go with that.

```py
@deconstructible
class FileSystemStorage(Storage):
    """
    Standard filesystem storage
    """

    def __init__(self, location=None, base_url=None, file_permissions_mode=None,
                 directory_permissions_mode=None):
        self._location = location
        self._base_url = base_url
        ...
```
