### ISSUE TITLE
FYI: I'm forking this project, at least temporarily.

### ISSUE THREAD

**Issue by thomasf** [py-pa/django-minio-storage#23]
I have too many upcoming changes which depends on my current pull requests here..

I created a new github org today to handle the current list of forks of I and some other people need on pypi ( https://github.com/py-pa/ ) .  

I moved my personal fork to https://github.com/py-pa/django-minio-storage , will set things up during the next days.

For the time being `py-pa` has  three main goals:

- disconnect projects from personal github user accounts and collect them under a common place.
- set up CI to auto publish tagged releases to `pypi.python.org`
- prepare packages so they can be moved to `jazzband` OR collaborate within the `py-pa` org (after jotting down some simple ground rules to clarify how org wide or project wide maintenance should work)..

**Comment by thomasf** [comment]
The only current functional change in the fork  is that python 2.7 is explicitly not supported.

**Comment by jezdez** [comment]
Hello, (a [jazzband](https://jazzband.co/) roadie here), after talking with @thomasf / a00001 on IRC (#jazzband on Freenode) I'd like to say that hard forks are never a solution to get PRs released on PyPI. I encouraged them to talk to @tomhoule instead to collaborate on fixes. FTR Jazzband does not promote or encourage such fork patterns as it increases the chance for maintenance disruption.

**Comment by thomasf** [comment]
I've added hopefully clear large and clear notice to the fork's readme which states that the version over there might be removed from both github and pypi.org in time depending on how things evolve.. 

 https://github.com/py-pa/django-minio-storage#important-note-about-this-fork

**Comment by tomhoule** [comment]
Hey, original author of the library here. I'm sad not to have been able to dedicate time to maintenance, and I'm afraid the prospects don't look much better in the near future.

In the interest of the library, I'm ready to transfer ownership to a willing maintainer. You can contact me at tom at tomhoule.com to discuss that.
