### ISSUE TITLE
Understanding `MINIO_STORAGE_STATIC_URL`

### ISSUE THREAD

**Issue by sivabudh** [py-pa/django-minio-storage#39]
I have Django and Minio servers running on the same server (VM).

When Django performs static files collection or uploading files from app to Minio, I would like it to (for performance reason) communicate with Minio server via `localhost`. Of course, these files are still served over the internet via the public domain URL. 

If this is the intent, are configurations below correct?

Assuming that minio is running on the default port 9000 and the public domain name is: `my.site.com`

MINIO_STORAGE_ENDPOINT = 'my.site.com'
MINIO_STORAGE_MEDIA_URL = 'http://localhost:9000/media'
MINIO_STORAGE_STATIC_URL = 'http://localhost:9000/static'

**Comment by sivabudh** [comment]
More precisely, when I collect static, does it utilize `my.site.com` or `localhost` ?

**Comment by sivabudh** [comment]
We did further tests. We are wondering if `MINIO_STORAGE_MEDIA_URL` and `MINIO_STORAGE_STATIC_URL` are used by the library at all?

We have `minio` running on `localhost:9000` but when we, for example, changed `MINIO_STROAGE_MEDIA_URL` to be `localhost:9001`, it had no effect at all.

Did we misunderstand or these 2 variables are not really being used by the library?

**Comment by thomasf** [comment]
collectstatic does not work, see other issues.

**Comment by sivabudh** [comment]
@thomasf thanks for your response. Actually, we got collectstatic to work just fine. What we are trying to do or the problem we are running into is how to collectstatic over localhost but define the endpoint as a public domain.

**Comment by thomasf** [comment]
I'm closing this issue. 
You might have resolved this now but the MINIO_STORAGE_`..._URL settings are advised against in the documentation because they are complicated and can cause problems:
 https://github.com/py-pa/django-minio-storage/blob/master/docs/usage.md
You have to figure out how they can work for you if you need them,
