### ISSUE TITLE
Update PyPI index

### ISSUE THREAD

**Issue by TAnas0** [py-pa/django-minio-storage#48]
Hey there,

I have been using your package and I noticed that the version [installed](https://pypi.python.org/pypi/django-minio-storage) using `pip install django-minio-storage` is not up to date with the GitHub repository.
This lead to confusion since I didn't recheck the version installed after the command and confused me. :sweat_smile:

I resorted at the end to installing it using the command `pipenv install git+https://github.com/py-pa/django-minio-storage.git#egg=django-minio-storage
` wich was suggested to me after I asked this [SO question](https://stackoverflow.com/questions/47018200/importerror-raised-trying-to-import-a-function/47036834?noredirect=1#comment81020166_47036834). Doing so led to some problems concerning my packages and the `requirements.txt` file.

I'd like also to note that I noticed several good changes between the version in PyPI and your repository, so I think synchronizing them will help other people use your package more efficiently.

Thank you in advance

**Comment by thomasf** [comment]
There are a few  issues I want to have resolved until a 0.2 release on pypi but it's almost there.  Your requrements.txt situation should not be related to the package installation method used.

**Comment by thomasf** [comment]
0.2 is released now.
