### ISSUE TITLE
Add ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by arashyousefi** [py-pa/django-minio-storage#50]
Hello

It would be really nice to add a storage class that supports manifesting static files.

**Comment by thomasf** [comment]
You can try to extend `MinioStaticStorage` with Djangos `ManifestFilesMixin` into your own project local stroage class. I don't know if will work or not but it might.

**Comment by arashyousefi** [comment]
Sadly it does not. Though i only spent an hour or two on the issue.

**Comment by douglasmiranda** [comment]
With Django 2.2 and django-minio-storage 0.2.2 it's working.

storage.py
```python
from django.contrib.staticfiles.storage import ManifestFilesMixin
from minio_storage.storage import MinioStaticStorage

class ManifestFilesMinioStaticStorage(ManifestFilesMixin, MinioStaticStorage):
    pass

```

settings.py
```python
STATICFILES_STORAGE = "my_project.storage.ManifestFilesMinioStaticStorage"
```
