### ISSUE TITLE
how can make it work with django1.4.2

### ISSUE THREAD

**Issue by pk026** [py-pa/django-minio-storage#55]
I have django 1.4.2 installed for project ..and I want to use django-minio-storage when I am installing it also upgrades my django version. when I revert django version its giving me "No Module named deconstruct"

as its not easy to upgrade django in one from 1.4.2 to 1.11.11. I want to make it work for 1.4.2 please help do that.

**Comment by thomasf** [comment]
We only support django 1.8 or later.. We pretty much will align with the official django support ( https://www.djangoproject.com/download/ ) for new releases. You have to backport django-minio-storage to older django versions yourself if you need it, you can just copy the code into your legacy project and make it work there in place..
