### ISSUE TITLE
Import error with minio >= 4.0.0

### ISSUE THREAD

**Issue by t0xicCode** [py-pa/django-minio-storage#59]
It seems that `minio >= 4.0.0` removed the `minio.policy` module. This module should be update to either follow the new minio implementation or to restrict the valid minio versions.

```
  File "/usr/local/lib/python3.5/site-packages/minio_storage/storage.py", line 16, in <module>
    from minio.policy import Policy
ImportError: No module named 'minio.policy'
```

**Comment by t0xicCode** [comment]
Nevermind, operator error.

**Comment by thomasf** [comment]
I'd rather leave pinning maximum versions up to the projects using the package using requirements.txt or something similar.
