### ISSUE TITLE
Make the tests work with Python 2.7

### ISSUE THREAD

**Issue by tomhoule** [py-pa/django-minio-storage#6]
Currently, there is a problem with unicode file names.

**Comment by tomhoule** [comment]
After more investigation, it appears that the problem occurs because of improper unicode handling in python 2.7's urllib. UTF-8 file names cannot be joined at some point. It would be great to find a solution that does not involve a lossy conversion of all file names to ascii.

**Comment by tomhoule** [comment]
I'm now thinking of not trying to support python 2 actively, since it's on the way to deprecation and we lack the time resources, unless somebody is interested on maintaining support themselves.

**Comment by thomasf** [comment]
I support dropping py2!

**Comment by fazpu** [comment]
I agree with dropping python 2.
