### ISSUE TITLE
Support non-public media files?

### ISSUE THREAD

**Issue by spapas** [py-pa/django-minio-storage#60]
Hello, I want to use minio along with django-minio-storage for storing uploaded media files for my users.

The thing is that I don't want all these uploaded files to be seen by all users but I want to have an access check before downloading each file. Only if the check passes the file will be actually downloaded (for example, a simple check is to only allow each user to download the file he has uploaded).

The easy way to do this is to do the check in django and, if the check passes connect to minio through django, download the file and pass it to the user. As you probably understand this is a major no-no since you should never serve static or media files through your django applications for reasons that should be all too obvious.

In any case, the proper way to handle this using normal media files (along with an http server that supports the  X-Sendfile functionality) is with django-sendfile (https://github.com/johnsensible/django-sendfile), i.e you create a ``get_file`` method that will do the actual permission check and if it passes it will send the  X-Sendfile header to nginx to actually return the file (or else it will return an 403-Access denied). This combines the best of both worlds, do any permission check you want in django and then notify the nginx (web server) to actually serve the file without any more effort on the django app.

I wasn't able to find something similar for django-minio-storage. From what I could understand, in minio each bucket can have a special access control that can be either public/download/upload or none. This seems like all or nothing; is there a way to have the fine-grained control I need using minio and django-minio-storage? 

Please keep in mind that I don't want to actually serve the file through my django app only to do the check in django and if it passes serve it through minio; but only to users that pass the check.

**Comment by spapas** [comment]
After some more research I stumbled upon generating urls for sharing, i.e using the following snippet:

```
import boto3
from botocore.client import Config


s3 = boto3.client('s3',
                    endpoint_url='http://localhost:9000',
                    aws_access_key_id='',
                    aws_secret_access_key='',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')


url = s3.generate_presigned_url(
    ClientMethod='get_object',
    Params={
        'Bucket': 'better-minio-upload-media',
        'Key': '100_0418a_53w6XD4.jpg'
    }
)

print(url)
```

I could generate a url that when used in a non-authenticated browser could retrieve the ``100_0418a_53w6XD4.jpg`` object even though the ``better-minio-upload-media`` folder had a ``none`` access policy. Is this the correct way to go for my requirement? I.e create a view that will do the actual permission check in django and if the check passes will redirect to a generated presigned url for that specific media file? Is there an easy way to get the bucket name and the key for a django file upload (``FileField``) ?

Also is there a way to actually integrate the generate_presigned_url() method to the file field object i.e in addition to using the file.url that will return the private file url (i.e something like 'http://localhost:9000/better-minio-upload-media/100_0418a_53w6XD4.jpg') to also add a file.presigned_url() method that will return the public url (i.e something like http://localhost:9000/better-minio-upload-media/100_0418a_53w6XD4.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=PNRX0CDHHU5E2ZXTGTHO%2F20180610%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180610T135112Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=8d45962e55284f9476c337a000e54ce26e2062d712c56c342df2c15c3fea8ec3)


TIA

**Comment by thomasf** [comment]
When you have the bucket set up to not allow reads unless the urls are signed the signed url must always be used, there is ot "private" url..

**Comment by thomasf** [comment]
For this special use case you should probably implement your own redirection end point.. But why not just use signed urls everywhere and only send/render the links which the user has access to.

**Comment by spapas** [comment]
Hello, yes probably that's what I'll need to do. Please notice that this is not so special use case it is a rather common requirement to check for permissions before serving media files (that's why the X-Sendfile header actually exists).

**Comment by thomasf** [comment]
You can also define as many minio storage classes as you want in you app. You don't have to use the Media/Static-storage classes, those are just for the convenience of using django settings for configuration .. Just create new sublcasses, each filefield can have it's own storage class.

**Comment by thomasf** [comment]
I am btw. thinking of about how to provide the best simplified superclass interface for to getting django settings as noted in this comment which also is an example of a subclass using it's own bucket 
https://github.com/py-pa/django-minio-storage/issues/62#issuecomment-397223144

**Comment by thomasf** [comment]
I've created an example test of a custom storage class https://github.com/py-pa/django-minio-storage/blob/master/tests/test_app/tests/custom_storage_class_tests.py
