### ISSUE TITLE
How can I specify the read presigned url exipry.  

### ISSUE THREAD

**Issue by adilmalik393** [py-pa/django-minio-storage#62]
Is there any way to specify presigned url expiry time. If i want my object to be accessed only within 1 hour. How do i do that ?

**Comment by adilmalik393** [comment]
Right now, This library doesn't give this feature. In my opinion, There should be a django setting variable with MINIO_PRESIGNED_EXPIRY_TIMEDELTA

**Comment by thomasf** [comment]
yeah, it should probably be a per storage setting.

**Comment by thomasf** [comment]
Or maybe we should promote sub classing for deeper configuration...

This could be made easier to use, maybe a proper base class or something:

```py
## Application specific storage class
from django.utils.deconstruct import deconstructible
from minio_storage.storage import (
    MinioStorage, create_minio_client_from_settings, get_setting
)


@deconstructible
class MinioUserDataExportStorage(MinioStorage):
    def __init__(self):
        client = create_minio_client_from_settings()
        bucket_name = get_setting(
            "MINIO_STORAGE_USER_DATA_EXPORT_BUCKET_NAME")

        super(MinioUserDataExportStorage, self).__init__(
            client, bucket_name,
            presign_url=True,
            auto_create_bucket=True,
            presign_urls=True)


storage = MinioUserDataExportStorage()
```

At some point, code makes more sense than settings..

**Comment by thomasf** [comment]
max_age argument added to storage.url method
