### ISSUE TITLE
Ephemeral port exhaustion when accessing large amounts of stored objects

### ISSUE THREAD

**Issue by caseybrichardson** [py-pa/django-minio-storage#66]
Recently I've been doing some work using this library in combination with django management commands to make exporting large amounts of data easy. For several days I was stuck with an error that seemed to be related to the number of calls I was making to minio to fetch stored images. After fetching 28,231 objects from minio, I was receiving this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
```

 At first I believed this to be because the underlying sockets were getting stuck in TIME_WAIT, but had some difficulty testing that hypothesis. After some playing around with solutions, it seems to have actually been a garbage collection issue. Even though the library calls `self.file.close()` and `self.file.release_conn()` on the underlying file object, the reference to the HTTPConnection that is used to read from minio stays around and given enough requests are made, ties up the system so that no further requests can be made.

My solution to this was to manually set the filefields `file` property to `None`. I have created a custom storage that uses the `ReadOnlyMinioObjectFile`, but this issue seemed to be present on both classes. The solution I used:

```
# image is a model object, and data is a filefield on that object that uses minio as it's storage
with image.data.open('rb') as file_data:                                                                    
    data_bytes = file_data.read()                                                                 
    file_data.file = None  # Without this line, the process will fail after enough connections                                     
```

My use case is definitely an edge case and this problem probably wouldn't affect most users, but I thought it'd still be a good idea to put this out there in case anyone else ran into it.

**Comment by thomasf** [comment]
Hmm, is this maybe a bug in the minio client library then? close/release_conn should be enough (IIRC) ?

**Comment by thomasf** [comment]
I don't know how django creates/manages instances of storage classes, the connections are probably not resued if django for some reason creates different instances of the storage backend for each request.. Worth verifying at least..

**Comment by caseybrichardson** [comment]
In my testing I did some logging of the PoolManager instance that the Minio client library uses internally and it was the same instance for each request. I'll see if I can replicate this problem in a test to make it easier to debug.

**Comment by thomasf** [comment]
@caseybrichardson Did you arrive at any conclusion?

**Comment by caseybrichardson** [comment]
Sorry about not producing any results on this. Shortly after encountering this issue we actually phased minio use out of our stack. As such I'm unable to provide any more details on the cause of this issue.

**Comment by thomasf** [comment]
Ait., thanks anyway
