### ISSUE TITLE
Unable to Use plugin for Django Media

### ISSUE THREAD

**Issue by ghost** [py-pa/django-minio-storage#68]
Just installed the app, seems fine but who can i use it for my media files?
i'm only getting it to work for my static files.

this is what my config looks like:

```
#S3 Storage

STATIC_ROOT = './static_files/'
STATIC_URL = '/static/'
MEDIA_ROOT = './media_files/'
MEDIA_URL = '/media/'


DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = '127.0.0.1:9000'
MINIO_STORAGE_ACCESS_KEY = 'W3XRS0AK3J1PXHOQPIPK'
MINIO_STORAGE_SECRET_KEY = 'aF72q5G4ZFhfOwoThzFhyzh3aqZoiZBPpse1HVWO'
MINIO_STORAGE_USE_HTTPS = False
MINIO_STORAGE_MEDIA_BUCKET_NAME = 'media'
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
MINIO_STORAGE_STATIC_BUCKET_NAME = 'static'
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
MINIO_STORAGE_STATIC_USE_PRESIGNED = True
MINIO_STORAGE_MEDIA_USE_PRESIGNED = True
```

urls.py:
```
...

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


```
i also thought about to set:
```
MINIO_STORAGE_MEDIA_URL = 'http://127.0.0.1:9000/media'
MINIO_STORAGE_STATIC_URL = 'http://127.0.0.1:9000/static'
```
but it seems they are getting ignored.

Any idea what could be the issue here?
the bucket(s) are getting created but the url django calls for media files is 127.0.0.1:8000, to the local django webserver and not the minio server like it does for static files (127.0.0.1:9000)

many many thanks in advance.

**Comment by thomasf** [comment]
it should work OOTB for media. How do you create the urls to the media files?

**Comment by venomone** [comment]
What do you mean with create?
i guess you have to give me a hint here, im new to Django since 4 month :(
Im on Django 2.1.2
many thanks in advance

**Comment by ghost** [comment]
> it should work OOTB for media. How do you create the urls to the media files?

What do you mean with create?
i guess you have to give me a hint here, im new to Django since 4 month :(

urls:
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Im on Django 2.1.2
many thanks in advance
