### ISSUE TITLE
How to save file to local?

### ISSUE THREAD

**Issue by lynkas** [py-pa/django-minio-storage#69]
For example, when user upload a video, I might need to process it with ffmpeg. So firstly, I need to save video to local disk. How to do this?

**Comment by douglasmiranda** [comment]
Let's say you are using django-storages or equivalent, so your files are going to S3 or whatever cloud storage you choose. And I'm assuming by local you mean the same server your Django app is running, or at least a mounted volume.

You can use the `FileSystemStorage` for that field, then in another task/function, after the ffmpeg process, you send to S3, for example.

https://docs.djangoproject.com/en/2.2/topics/files/#the-built-in-filesystem-storage-class

**Comment by thomasf** [comment]
You can handle the files from the form in a view to process them while they are UploadedFile objects before they are put into a remote storage.
