### ISSUE TITLE
Support Django 1.10

### ISSUE THREAD

**Issue by tomhoule** [py-pa/django-minio-storage#7]
The release has just been announced.
https://docs.djangoproject.com/en/1.10/releases/1.10/
- File storage should apparently return timezone-aware datetime objects. I will investigate that shortly.
- There is a new `Storage.generate_filename()` method, to be investigated as well.

**Comment by elcolie** [comment]
1.11 now

**Comment by fazpu** [comment]
Should be solved with https://github.com/tomhoule/django-minio-storage/pull/14

**Comment by tomhoule** [comment]
#14 has been merged, feel free to reopen if this is not solved :)
