### ISSUE TITLE
Is it possible to add a url time setting?

### ISSUE THREAD

**Issue by Sunnnner** [py-pa/django-minio-storage#71]
def url(self, name, expires=timedelta(days=7)):
        # type: (str) -> str

        # NOTE: Here be dragons, when a external base_url is used the code
        # below is both using "internal" minio clint APIs and somewhat
        # subverting how minio/S3 expects urls to be generated in the first
        # place.
        #
        if self.presign_urls:
            url = self.client.presigned_get_object(self.bucket_name, name, expires=timedelta(days=7))
            if self.base_url is not None:
                parsed_url = urlparse(url)
                path = parsed_url.path.split(self.bucket_name, 1)[1]
                url = '{0}{1}?{2}{3}{4}'.format(
                    self.base_url, path, parsed_url.params,
                    parsed_url.query, parsed_url.fragment)

**Comment by Sunnnner** [comment]
please

**Comment by thomasf** [comment]
Add a test and create a pull request if you want it fast.

The url function argument should probably default to `expires=None` though and just use the default values in minio client.
