### ISSUE TITLE
Disk Cache + s3 gateway

### ISSUE THREAD

**Issue by douglasmiranda** [py-pa/django-minio-storage#72]
When using [Disk Cache](https://docs.min.io/docs/minio-disk-cache-guide.html) I see no improvement in the speed of `collectstatic`.

I wonder why because inside the Minio container I can see the files available locally.

And I'm running `collectstatic` without changing anything. 

```
Minio Server: 2019-04-09T01:22:30Z

PYTHON_VERSION=3.7.3

Django==2.2

django-minio-storage==0.2.2
  - django [required: >=1.8, installed: 2.2]
    - pytz [required: Any, installed: 2019.1]
    - sqlparse [required: Any, installed: 0.3.0]
  - minio [required: >=4.0.3, installed: 4.0.14]
    - certifi [required: Any, installed: 2019.3.9]
    - python-dateutil [required: Any, installed: 2.8.0]
      - six [required: >=1.5, installed: 1.12.0]
    - pytz [required: Any, installed: 2019.1]
    - urllib3 [required: Any, installed: 1.24.1]
```

**Comment by thomasf** [comment]
Why would the speed of collectstatic increase with disk cache?

**Comment by douglasmiranda** [comment]
I was thinking it would make faster after the first time because the checking for what was changed would be using the locally cached files. But I'm guessing it doesn't work that way then.

**Comment by thomasf** [comment]
I don't know but I think you have to investigate exactly how disk cache works before creating an issue here, if there is an issue I would expect that it could also be in the minio python client library if it uploads the same files even if it doesn't have to. I guess it could be that most static files are so small that just doing a header check aginst an upstream object storage will take about as long time as uploading the actual file (if that is done).

**Comment by douglasmiranda** [comment]
Makes sense, I will investigate!
