### ISSUE TITLE
What is the difference between internal access and external access of django-minio-storage

### ISSUE THREAD

**Issue by Sunnnner** [py-pa/django-minio-storage#77]
The access I make inside docker is the service name: port number. The user needs to access minio-storage. How should I set it?

**Comment by thomasf** [comment]
you should only use a publicly facing TLS terminated public URL that both django and the end users access. Setup some subdomain to your website like minio.yourdomain.com for that

**Comment by Sunnnner** [comment]
Thank you for your answer，one more question, can I set MINIO_STORAGE_MEDIA_URL to give users access to the outside world?
