### ISSUE TITLE
Storing media files only works partly

### ISSUE THREAD

**Issue by ghost** [py-pa/django-minio-storage#80]
I'm currently try to integrate S3 as a storage backend for media files and also for static files.

With static files I have no problems at all, but if I want to upload media files I get form validation errors and stuff like that, I get problems.

That's the first thing with media files. The second is that, for some reason, if i place the file at the template, Django returns a local path instead of the path to the s3 service (minio) as it also does for static files, I'm not really sure where this behaviour comes from, but it might be a problem of how I process the return of the saved file path.

models.py:

```
    def get_file_path_user_avatar(filename):
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (uuid.uuid4(), ext)
        return os.path.join('user_avatar', filename)
    
    class User(AbstractBaseUser):
        user = models.CharField(verbose_name='Username', max_length=15, unique=True)
        bio = models.TextField(verbose_name='Bio', blank=True, null=False, max_length=1000)
        avatar = models.ImageField(
            null=False,
            blank=True,
            upload_to=get_file_path_user_avatar,
            validators=[default_image_size, default_image_file_extension],
        )
    ...

```
The funny fact is that I'm able to upload the file at the Django admin backend but not at my frontend. The form does not validate at the frontend, but the files get saved anyways.

This is how I display the avatar image.

template.html:

   ` <img class="avatar" src="/media/{{ user.avatar }}">
`
This is how I do it with static files:

   ` <img class="avatar" src="{% static '/sys_img/no_image.png' %}">`

which is again working fine.

settings.py:

   ```
 DEFAULT_FILE_STORAGE = 'minio_storage.storage.MinioMediaStorage'
    STATICFILES_STORAGE = 'minio_storage.storage.MinioStaticStorage'
    MINIO_STORAGE_ENDPOINT = 's3-service:9000'
    MINIO_STORAGE_STATIC_BUCKET_NAME = "static"
    MINIO_STORAGE_MEDIA_BUCKET_NAME = "media"
    STATIC_URL = f'http://{MINIO_STORAGE_ENDPOINT}/{MINIO_STORAGE_STATIC_BUCKET_NAME}/'
    MEDIA_URL = f'http://{MINIO_STORAGE_ENDPOINT}/{MINIO_STORAGE_MEDIA_BUCKET_NAME}/'
    MINIO_STORAGE_USE_HTTPS = False
    MINIO_STORAGE_MEDIA_USE_PRESIGNED = True
    MINIO_STORAGE_STATIC_USE_PRESIGNED = True
    MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
    MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = True
    MINIO_STORAGE_ACCESS_KEY = 'ATSFDWTAGF6GDB7DGA1D'
    MINIO_STORAGE_SECRET_KEY = 'ifvzb134o084bk87413b340mfc34g081'
```

My guess is that this behaviour maybe comes from:

  ```
  ext = filename.split('.')[-1]
    return os.path.join('user_avatar', filename)

```
currently the following sting gets saved at the DB for that field:

user_avatar/40635ccd-40c2-41f3-b244-82c160657b9b.png

Thankful for any help or ideas.

**Comment by thomasf** [comment]
It's ```<img class="avatar" src="{{ user.avatar.url }}">``` or something similar
