### ISSUE TITLE
Any known uses of this library in production?

### ISSUE THREAD

**Issue by sivabudh** [py-pa/django-minio-storage#9]
I'm considering using this library for production. Shall I bite the bullet? 😁

**Comment by tomhoule** [comment]
I am the original author of the library and I don't use it in production anymore (I don't write too much python these days). I will try to make time soon to keep the library up to date and release a 0.2, and I am definitely available for support or issues. However it's clearly not battle-tested yet, and as you may have noticed has not had active development for a few months, but it's not abandoned either, and I would be very happy of course to have more people on board :)

**Comment by saily** [comment]
@sivabudh did you bite the bullet? 
I'm considering using this as well so it would be great if you could share some experience.

**Comment by tomhoule** [comment]
The library hasn't been updated in a while, I've been swamped with other projects. Since there seems to be interest in it I'll try to make some time for it this month.

**Comment by fazpu** [comment]
Major update coming with https://github.com/tomhoule/django-minio-storage/pull/14. I plan to use it in production.

**Comment by thomasf** [comment]
I will start using this in production in a few days.. I am currently using a patched version which is a almost only a merge of my current pull requests.  I do want a couple of other things from it but that's just features, nothing which limits general use like #19 and #16 does.
