### ISSUE TITLE
Is Minio Standalone Erasure Code supported?

### ISSUE THREAD

**Issue by fkromer** [py-pa/django-minio-storage#92]
I'm using `django-minio-storage` with a single USB drive as storage in an experimental environment. Uploading and changing files via models which have `models.FileField()` works just fine in this setup.

However when I try to enable [MinIO "Standalone Erasure Code"](https://docs.min.io/docs/minio-erasure-code-quickstart-guide.html) I have strange behaviour.

I've mounted 4 USB sticks into these dirs:

    /media/external/storage-sda
    ...
    /media/external/storage-sdd

In `docker-compose` I've this config for a minio service (excerpt):

```
services:
  minio:
    volumes:
      - /media/external/storage-sda:/data/minio1:rw
      ...
      - /media/external/storage-sdd:/data/minio4:rw
    command: server /data/minio{1...4}
```

This are the Django settings for minio:

    MINIO_STORAGE_MEDIA_BUCKET_NAME='bucket'
    MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = True
    MINIO_STORAGE_MEDIA_URL = None

When running `docker-compose up` the output of minio is as it should be:

    Formatting 1 zone, 1 set(s), 4 drives per set.
    Status:         4 Online, 0 Offline.

A file for a model can be uploaded and ends up in minio `bucket/bucket/<dir-set-in-upload-to>/<file>`. **However before using erasure code setup they ended up in `bucket/<dir-set-in-upload-to>/file` instead. When uploading a new file for the model the old one is not deleted, the new one is just added. In the model change view there is no button to change the file anymore.**

The only thing I changed when migrating from single to several USB sticks was duplicating the volumes entries `/data/minio` to `/data/minio1`, `/data/minio2`, ... and changing the minio start command from `server /data/minio` to `server /data/minio{1...4}`. When I use the alternative start command `server /data/minio{1...4}/tenant` which supports multiple tenants (https://www.youtube.com/watch?v=CdCJozrwBxE) instead of `server /data/minio{1...4}` I've exactly the same behaviour.

Do I have to set MINIO_STORAGE_MEDIA_URL explicitly?

**Comment by thomasf** [comment]
I don't know. IIRC Erasure Code mode should not matter to s3 api clients at all since it's just change to the storage backend

**Comment by fkromer** [comment]
Right. It seems like this issue relates to how `models.FileFIeld()` is configured. But I'm not sure yet.

**Comment by thomasf** [comment]
I don't think we have any actual model tests so if there are edge cases where FileField configurations causes confusion for the storage it might very well have some bugs.

**Comment by fkromer** [comment]
One point to consider is that the field must be "clearable", means the field needs to have `blank=True` set: `file = models.FileField(upload_to="directory/", blank=True)`. I removed `blank=True` by accident. That was the reason for the gone checkbox button "Clear".

However if I check the files in the minio server via it's web ui (`<minio-server-url>:9000`) I still see the old files. Neither clearing it via the admin interface button removes the file, nor is it  replaced when browsing and uploading a file in the model change form.

**Comment by thomasf** [comment]
Files are never removed. It's not a feature, django never deletes files on new uploads or model removals. You have to write code to handle deletes of unused files yourself.

**Comment by fkromer** [comment]
The behavior makes total sense then. I never cared about yet but recognized that if a file already exists an uploaded file with the same name is extended with a random extension to the file name. Sorry for wasting your time.
