### ISSUE TITLE
Management command to upload file

### ISSUE THREAD

**Issue by jayvdb** [py-pa/django-minio-storage#93]
I wasnt able to find a management command which uploads files to minio.

django-extensions 's `sync_s3 --media-only` would be perfect, however it depends on `boto`, has different setting names, and also didnt work out of the box for me.

So I built a quick uploader based on https://github.com/kneufeld/minio-put .  It seems like a natural fit to add into https://github.com/py-pa/django-minio-storage/blob/master/minio_storage/management/commands/minio.py

**Comment by thomasf** [comment]
Maybe, you can also just use mc (mc mirror is great) or any other available s3 command line client to do that.. I'm not sure I want to maintain too many features that are easily available by just installing another tool.

**Comment by jayvdb** [comment]
I am not going to add `mc` to my Docker image for a backend server - both security and image size, and image build duration.  The django cmd `minio` already has most CRUD operations, so why not have a complete set, but keep them basic?

Anyways, if not wanted here, I can inquire at other similar extensions, or create my own to host this little helper.

**Comment by thomasf** [comment]
You don't need to add mc to your docker image, you can use the official mc image,    https://hub.docker.com/r/minio/mc/

**Comment by thomasf** [comment]
The thing is that mc can do a lot more like mirror one s3 bucket to another with or without deletion. It can also do recursive copies from/to local filesystems and it's written in go so it's already just a single statically linked binary that is very easy to install however you like.

**Comment by thomasf** [comment]
The reason I added the minio command was so that it would be possible to initialize new instances from scratch automated using only the django project itself. Being able to create buckets and set policies was important for that purpose.  Just look at mc's mirror code, its almost 1000 loc https://github.com/minio/mc/blob/master/cmd/mirror-main.go , even if it isn't hard it's not super trivial to implement and probably requires lots and lots of tests.. Personally I would not even have a use case for copying to local file system, it would have to support s3 to s3 because I need to know that s3 object metadata is kept.

**Comment by jayvdb** [comment]
Adding a mc docker image is overkill, and undesirable as it would slow down CI and CD.

My use case is copying individual files from the django image to the newly minted minio instance.  As mentioned at the outset, https://github.com/kneufeld/minio-put is the code I adapted to solve my problem.  Very simple.  I am happy to add 100% test coverage for the extra functionality I add here.  If you really dont want it, close the issue and I will find another long term home for this, no drama.

**Comment by thomasf** [comment]
Sure, add a simple put command but please no fancy features since it will have to be supported. If you add a put command you should maybe also  add an get command, idk..

**Comment by thomasf** [comment]
My suggestion would be to use the syntax

```
manage.py minio put [-r/--recursive]  [--overwrite] source-path dest-path
manage.py minio get [-r/--recursive] source-path dest-path
```

if --overwrite isn't specified the command should probably fail if an object already exist.
 Maybe --overwrite should exist on both commands, maybe it could be called -f/--force to be closer to rm/mv/cp

Please let's come to an agreement of the exact workings before you implement it.

**Comment by thomasf** [comment]
closing due to age
